### ISSUE TITLE
Error : java.lang.NoSuchFieldException: language

### ISSUE THREAD

**Issue by Batsave** [Majhrs16/ChatTranslator#3]
Hello, 
I open an issue for a lang detection problem under Mohist 1.20.1

`[16:31:54 ERROR]: me.majhrs16.cht.util.LocaleUtil.getPlayerLocale: java.lang.NoSuchFieldException: language
[16:31:54 INFO]:  | BATSAVE_ > Test
[16:31:55 INFO]:        [FR] Test
[16:31:55 INFO]:  BATSAVE_ → Test
[16:31:57 ERROR]: me.majhrs16.cht.util.LocaleUtil.getPlayerLocale: java.lang.NoSuchFieldException: language
[16:31:57 INFO]:  | BATSAVE_ > sqdqsd
[16:31:57 INFO]:        [FR] sqdqsd
[16:31:57 INFO]:  BATSAVE_ → sqdqsd`

According to the error he would not have access to the player's default language resource

Do you have any solutions to offer us?

**Comment by Batsave** [comment]
We often get this kind of error too.

`
[16:15:27 ERROR]: Could not pass event PlayerInteractEvent to ChatTranslator v2.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge-1.20.1-47.3.1-universal.jar%23327!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.3.1-universal.jar%23327!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:602) ~[forge-1.20.1-47.3.1-universal.jar%23327!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:586) ~[forge-1.20.1-47.3.1-universal.jar%23327!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:555) ~[forge-1.20.1-47.3.1-universal.jar%23327!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:517) ~[forge-1.20.1-47.3.1-universal.jar%23327!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:178) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1530) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:992) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23322!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "lang" is null
        at me.majhrs16.cht.util.util.convertStringToLang(util.java:39) ~[?:?]
        at me.majhrs16.cht.events.Signs.updateSign(Signs.java:51) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor320.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.3.1-universal.jar%23327!/:?]
        ... 23 more`

**Comment by Majhrs16** [comment]
If sign translation is not useful or necessary for you, disable `auto-translate-others.signs.enable`.
I have to say that until now, **ChT v2.0 does not officially support Mohist**.

Probably in Mohist 1.20.1, within the EntityPlayer class the name of the field containing the player's language has been changed.

I hope with v2.1 to support mods...

<details><summary>Relevant Java code:</summary>

```java
Method getHandle = player.getClass().getDeclaredMethod("getHandle");
getHandle.setAccessible(true);

Object entityPlayer = getHandle.invoke(player);

if (version <= 1201) { // 1.20.1
	fieldName = "locale";

} else if (version == 1202) { // 1.20.2
	fieldName = "cM";

} else if (version == 1204) { // 1.20.4
	fieldName = "cO";

} else if (version == 1206) { // 1.20.6
	fieldName = "dd";
}

if (fieldName != null)
	playerLocale = (String) entityPlayer.getClass().getField(fieldName).get(entityPlayer);
```
</details>

**Comment by Batsave** [comment]
thank you for the speed of response, I deactivate this option and I close this Issue, if you ever wish to test Mohist 1.20.1 to make it compatible do not hesitate to contact me and it will be a pleasure! 

Our server uses your plugin and we are more than happy with it! 

Thanks
